name: Run the tests on pull requests

on:
  pull_request:
    branches: [main]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        container: [1, 2, 3]
    env:
      CYPRESS_ENV: ${{ vars.ENV_TYPE }}
      SPLIT: ${{ strategy.job-total }}
      SPLIT_INDEX: ${{ strategy.job-index }}

    steps:
      - name: Git clone
        uses: actions/checkout@v4

      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Write cypress.env.json
        run: echo '${{ secrets.CYPRESS_ENV_FILE }}' > cypress.env.json

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress tests for ${{ env.CYPRESS_ENV }}
        uses: cypress-io/github-action@v6
        with:
          command: npx cypress run --env type-of-environment=${{ env.CYPRESS_ENV }} \
            --reporter mochawesome \
            --reporter-options overwrite=false,reportDir=cypress/results,json=true,html=false

      - name: Debug list JSON results
        run: |
          echo "Listing JSON in cypress/results"
          find cypress/results -name "*.json" || echo "No JSON found"

      - name: Upload test JSON results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: mochawesome-results-${{ matrix.container }}
          path: cypress/results

  merge-report:
    runs-on: ubuntu-latest
    needs: cypress-run
    steps:
      - uses: actions/checkout@v4

      - name: Download all test results
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Move all JSON to one folder
        run: |
          mkdir -p merged
          find artifacts -name "*.json" -exec cp {} merged/ \;

      - name: Copy videos and screenshots
        run: |
          mkdir -p merged/videos merged/screenshots
          find artifacts -type f -name "*.mp4" -exec cp {} merged/videos/ \;
          find artifacts -type f -name "*.png" -exec cp {} merged/screenshots/ \;

      - name: Merge Mochawesome JSON files
        run: |
          npx mochawesome-merge merged/*.json > merged/report.json

      - name: Generate HTML report with assets
        run: |
          npx marge merged/report.json \
            --reportDir merged \
            --inlineAssets \
            --charts

      - name: Upload final HTML report (with videos/screenshots)
        uses: actions/upload-artifact@v4
        with:
          name: final-mochawesome-report
          path: merged